language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
env:
 global:
    - GH_REF: github.com/bond-huang/navigator.git
branches:
  only:
    - main
script:
  - travis_wait 10 bash start.sh

