os: linux
arch:
  - ppc64le
language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
  - pip install -q -e .
branches:
  only:
    - main
env:
 global:
    - GH_REF: github.com/bond-huang/navigator.git
script:
  - python setup.py test

