language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
env:
 global:
    - GH_REF: github.com/bond-huang/navigator.git
script:
  - travis_wait 10 bash start.sh
after_script:
  - git clone https://${GH_REF} .temp
  - cd .temp
  - git checkout gh-pages
  - cd ../
  - mv .temp/.git dist
  - cd dist
  - git config user.name "huang"
  - git config user.email "huang19891023@163.com"
  - git add .
  - git commit -m "Update gh-pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
branches:
  only:
    - main
