language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
  - pip install pytest coverage
  - python setup.py -q install
branches:
  only:
    - main
script: 
  - coverage run -m pytest
  - coverage report

