language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
  - pip install pytest coverage
branches:
  only:
    - main
env:
 global:
    - GH_REF: github.com/bond-huang/navigator.git
script: 
  - pip install -e .
  - nohup waitress-serve --call 'nav:create_app' > nohup.log 2>&1 &
after_script:
  - cd ./dist
  - git init
  - git checkout --orphan gh-pages
  - git config user.name "${M_NAME}"
  - git config user.email "${M_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" main:gh-pages

