language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install Flask
  - pip install waitress
  - pip install pytest coverage
branches:
  only:
    - main
script: 
  - python3 setup.py

