DROP TABLE IF EXISTS links;

CREATE TABLE links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  maincategory TEXT NOT NULL,
  subcategory TEXT NOT NULL,
  urlname TEXT NOT NULL,
  urllocation TEXT UNIQUE NOT NULL
);